default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: alexberry
  password: ankl3Byt3r

development:
  <<: *default
  database: backbone_test_development

test:
  <<: *default
  database: backbone_test_test

